# Generated by Django 3.2.8 on 2021-10-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
